#!/bin/bash

# What's for lunch?
# $ lunch

TWTR_PATH="/1.1/statuses/user_timeline.json?screen_name=justeatmytweet&exclude_replies=true&include_rts=false&count=10"
JSON_PATH="[${1:-0}]entities.media[0].media_url_https"

open $(twurl $TWTR_PATH | json $JSON_PATH)

